import app.survey_vars as sv
from app.survey_classes import Divider, Question
from app.survey_vars import dub, list_dub, updated_vars

surveys = {
    'create_account': [
        Divider('Creating Dream Portal Account'),
        Question('First Name', 'textshort'),
        Question('Last Name', 'textshort'),
        Question('Phone', 'phone'),
        Question('Email', 'email'),
        Question('Country of Birth', 'textshort'),
        Question('Ethnicity', 'choice', choices=sv.ethnicity),
        Question('Birth Date', 'date'),
        Divider('Home Address', id=''),
        Question('Street', 'textshort'),
        Question('City', 'textshort'),
        Question('State', 'textshort'),
        Question('Zip', 'textshort', label='Zip Code *'),
    ],
    'app_type': [
        Divider('Select Scholarship Application'),
        Question('app_type', 'choice',
                 label='Which scholarship application will you be filling out?',
                 choices=[
                     ("hs_app", "High School Version"),
                     ("college_app", "College/University Version"),
                 ]),
    ],
    'mentor_sign_up': [
        Divider('General Information'),
        Question('First Name', 'textshort'),
        Question('Last Name', 'textshort'),
        Question('Email', 'email'),
        Question('Phone Number', 'phone'),
        Question('Birthday', 'date'),
        Divider('Home Address'),
        Question('Street', 'textshort'),
        Question('City', 'textshort'),
        Question('State', 'textshort'),
        Question('Zip', 'textshort', label='Zip Code *'),
        Divider('Mentoring Survey'),
        Question('works', 'textlong',
                 label='What is working? *'),
        Question('notworks', 'textlong',
                 label='What is not working? *'),
    ],
    'hs_app': [
        Divider('I. Academic Information'),
        Question('High_School_Name__c', 'textshort',
                 required=False, label='Name of High School *'),
        Question('High_School_City__c', 'textshort', required=False,
                 label='City where High School is located *'),
        Question('HS_GPA__c', 'number', required=False,
                 label='High School GPA *', max_digits=3, decimal_places=2),
        Question('SAT_Test_Scores__c', 'textshort', required=False,
                 label='Please enter your most recent SAT score, you will have a chance to upload your score later.'),
        Question('ACT_Test_Scores__c', 'textshort', required=False,
                 label='Please enter your most recent ACT score, you will have a chance to upload your score later.'),
        Question('List_of_Honors__c', 'textlong', required=False,
                 label='Please list any honors or awards you have received'),
        Question('English_Proficiency__c', 'choice', required=False,
                 label='How would you characterize your English-language proficiency?',
                 choices=[dub('Native speaker or equivalent'),
                          dub('Fluent but with an accent'),
                          dub('Reasonably Fluent'),
                          dub('Improving')]),

        Divider('II. Future College or University Information'),
        Question('First_Generation_Student__c', 'choice',
                 label='Would you be the first person in your family to attend college or university? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('Colleges_Applied_to__c', 'textlong', required=False,
                 label='Please list all colleges and universities you have applied to, or plan to appy to.  If you have already been accepted to a school, please note that as well *'),
        Question('Financial_Thoughts__c', 'multiplechoice', required=False,
                 label='A Dream Project Scholarship is renewable but will only pay for some of your college tuition.  Check all the boxes that apply as you consider your plan for paying for college *',
                 choices=sv.financial_thoughts),

        Divider('III. Community Involvement, Leadership and Employment'),
        Question('Identifies_as_Dreamer__c', 'choice',
                 label='Do you identify with the term "Dreamer"? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Divider('Please list up to five activities (one activity per text box below) that you are involved in. State the name of your role and describe your responsibilities.  This can include activities at school, sports, community, the arts or religious organizations. You can provide up to five activities.', id=''),
        Question('Activity_1__c', 'textlong', required=False,
                 label='Activity 1 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_2__c', 'textlong', required=False,
                 label='Activity 2 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_3__c', 'textlong', required=False,
                 label='Activity 3 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_4__c', 'textlong', required=False,
                 label='Activity 4 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_5__c', 'textlong', required=False,
                 label='Activity 5 Remember to state the name of your role and describe your responsibilities!'),
        Question('Employment__c', 'choice', required=False,
                 label="Employment Status", choices=sv.employ),
        Question('Employment_Description__c', 'textlong', required=False,
                 label='If you are employed, describe your job and your levels of responsibility.'),
        Question('Other_Responsibilities__c', 'textlong', required=False,
                 label='Do you currently have responsibilities to care for others (such as a child or family member)? Please explain *'),

        Divider('IV. Immigration Status'),
        Question('Favorite_Animal__c', 'choice', required=False,
                 label='What is your immigration status? *', choices=sv.status),

        Divider('V. Recommendations:'),
        Divider('Please include the name and contact information for two recommenders (at least one from a teacher or counselor).  The other can be someone you know though activities, school or work.', id=''),
        Divider('Recommender 1', id=''),
        Question('Name_Recommender_1__c', 'textshort',
                 required=False, label='Name *'),
        Question('Title_Recommender_1__c', 'textshort',
                 required=False, label='Title *'),
        Question('Email_Recommender_1__c', 'email',
                 required=False, label='Email *'),
        Question('Phone_Recommender_1__c', 'phone',
                 required=False, label='Phone *'),
        Divider('Recommender 2', id=''),
        Question('Name_Recommender_2__c', 'textshort',
                 required=False, label='Name *'),
        Question('Title_Recommender_2__c', 'textshort',
                 required=False, label='Title *'),
        Question('Email_Recommender_2__c', 'email',
                 required=False, label='Email *'),
        Question('Phone_Recommender_2__c', 'phone',
                 required=False, label='Phone *'),
        Divider('VI. Personal Statement'),
        Divider('In selecting Dream Scholars, the Dream Project is committed to serving students who have demonstrated perseverance in the face of adversity, hard work, and who have been resourceful.  Please write an original personal statement in which you tell us about yourself.  Feel free to describe some of your life experiences, both positive and negative, that have shaped your character, influenced your future life decisions and fueled your passions. You must upload your essay to the application in the next page. Please limit your essay to 1000 words. *', id=''),
        Divider('VII. Applicant’s Agreement and E-Signature'),
        Divider('If selected, I understand that if I do not remain in good academic standing, stay enrolled at least part time for the duration of my studies, and participate in some Dream Project activities, I risk forfeiting any subsequent Dream Project Scholarship funding', id=''),
        Question('E_Signature', 'textshort', label='E-signature *'),
    ],
    'college_app': [
        Divider('I. Academic Information'),
        Question('High_School_Name__c', 'textshort',
                 required=False, label='Name of High School *'),
        Question('High_School_City__c', 'textshort', required=False,
                 label='City where High School is located *'),
        Question('HS_GPA__c', 'number', required=False,
                 label='High School GPA *', max_digits=3, decimal_places=2),
        Question('SAT_Test_Scores__c', 'textshort', required=False,
                 label='Please enter your most recent SAT score, you will have a chance to upload your score later.'),
        Question('ACT_Test_Scores__c', 'textshort', required=False,
                 label='Please enter your most recent ACT score, you will have a chance to upload your score later.'),

        Divider('II. College or University Information'),
        Question('First_Generation_Student__c', 'choice',
                 label='Are you the first person in your family to attend college or university? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('Current_College__c', 'textshort', required=False,
                 label='Name of College/University you are currently attending *'),
        Question('Current_Major__c', 'textshort',
                 required=False, label='Major(s) *'),
        Question('Current_Minor__c', 'textshort',
                 required=False, label='Minor(s) *'),
        Question('Current_Number_of_Credits__c', 'number', required=False,
                 label='How many credits are you currently taking? *'),
        Question('College_GPA__c', 'number', required=False,
                 label='College/University GPA *', max_digits=3, decimal_places=2),
        Question('List_of_Honors__c', 'textlong', required=False,
                 label='Please list any honors, awards, or scholarships you have received'),
        Question('English_Proficiency__c', 'choice', required=False,
                 label='How would you characterize your English-language proficiency?',
                 choices=[dub('Native speaker or equivalent'),
                          dub('Fluent but with an accent'),
                          dub('Reasonably Fluent'),
                          dub('Improving')]),
        Question('Financial_Thoughts__c', 'multiplechoice', required=False,
                 label='A Dream Project Scholarship is renewable but will only pay for some of your college tuition.  Check all the boxes that apply *',
                 choices=sv.financial_thoughts_c),

        Divider('III. Community Involvement, Leadership and Employment'),
        Question('Identifies_as_Dreamer__c', 'choice',
                 label='Do you identify with the term "Dreamer"? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Divider('Please list up to five activities (one activity per text box below) that you are involved in. State the name of your role and describe your responsibilities.  This can include activities at your high school or college, sports, community, the arts or religious organizations. You can provide up to five activities.', id=''),
        Question('Activity_1__c', 'textlong', required=False,
                 label='Activity 1 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_2__c', 'textlong', required=False,
                 label='Activity 2 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_3__c', 'textlong', required=False,
                 label='Activity 3 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_4__c', 'textlong', required=False,
                 label='Activity 4 Remember to state the name of your role and describe your responsibilities!'),
        Question('Activity_5__c', 'textlong', required=False,
                 label='Activity 5 Remember to state the name of your role and describe your responsibilities!'),
        Question('Employment__c', 'choice', required=False,
                 label="Employment Status", choices=sv.employ),
        Question('Employment_Description__c', 'textlong', required=False,
                 label='If you are employed, describe your job and your levels of responsibility.'),
        Question('Other_Responsibilities__c', 'textlong', required=False,
                 label='Do you currently have responsibilities to care for others (such as a child or family member)? Please explain *'),

        Divider('IV. Immigration Status'),
        Question('Favorite_Animal__c', 'choice', required=False,
                 label='What is your immigration status? *', choices=sv.status),


        Divider('V. Recommendations:'),
        Divider('Please include the name and contact information for two recommenders (at least one from a teacher or counselor).  The other can be someone you know though activities, school or work.', id=''),
        Divider('Recommender 1', id=''),
        Question('Name_Recommender_1__c', 'textshort',
                 label='Name *', required=False,),
        Question('Title_Recommender_1__c', 'textshort',
                 label='Title *', required=False,),
        Question('Email_Recommender_1__c', 'email',
                 label='Email *', required=False,),
        Question('Phone_Recommender_1__c', 'phone',
                 label='Phone *', required=False,),
        Divider('Recommender 2', id=''),
        Question('Name_Recommender_2__c', 'textshort',
                 label='Name *', required=False,),
        Question('Title_Recommender_2__c', 'textshort',
                 label='Title *', required=False,),
        Question('Email_Recommender_2__c', 'email',
                 label='Email *', required=False,),
        Question('Phone_Recommender_2__c', 'phone',
                 label='Phone *', required=False,),
        Divider('VI. Personal Statement'),
        Divider('In selecting Dream Scholars, the Dream Project is committed to serving students who have demonstrated perseverance in the face of adversity, hard work, and who have been resourceful.  Please write an original personal statement in which you tell us about yourself.  Feel free to describe some of your life experiences, both positive and negative, that have shaped your character, influenced your future life decisions and fueled your passions. You must upload your essay to the application in the next page. Please limit your essay to 1000 words. *', id=''),
        Divider('VII. Applicant’s Agreement and E-Signature'),
        Divider('If selected, I understand that if I do not remain in good academic standing, stay enrolled at least part time for the duration of my studies, and participate in some Dream Project activities, I risk forfeiting any subsequent Dream Project Scholarship funding', id=''),
        Question('E_Signature', 'textshort', label='E-signature *'),
    ],
    'renewal_app': [
        Divider('I. Commitment to the Dream Project'),
        Question('Commitment_to_Dream_Project__c', 'multiplechoice', required=False,
                 label='You and/or your parents are expected to have participated in Dream Project activities. Check all the activities that you participated in this year *',
                 choices=[
                     dub('Holiday Dinner'),
                     dub('Awards Ceremony'),
                     dub('Fund Raising Activities'),
                     dub('Mentoring'),
                     dub('Public Speaking or Advocacy'),
                     dub('Participated with a Dreamer group at my college/university'),
                 ],),
        Question('Mandatory_Events__c', 'multiplechoice', required=False,
                 label='Please indicate which of the following mandatory activities you have participated in *',
                 choices=[
                     dub('Completed Fall Survey'),
                     dub('Wrote a thank you letter to a Named Scholarship donor'),
                     dub('Attended Summer Summit'),
                     dub('Beyond 12 (if applicable)'),
                 ],),

        Divider('II. Supporting Information'),
        Question('College_GPA__c', 'number', required=False,
                 label='College/University GPA *', max_digits=3, decimal_places=2),
        Question('Fall_History_of_Enrollment__c', 'number', required=False,
                 label=f"How many credits did you, or are you, currently taking? (Fall {updated_vars['summer_fall_s']}) *"),
        Question('Spring_History_of_Enrollment__c', 'number', required=False,
                 label=f"How many credits will you take in Spring {updated_vars['spring_s']}? *"),
        Question('Low_GPA_Explanation__c', 'textlong', required=False,
                 label='If your college GPA is below a 2.5, please explain'),
        Question('DNR_Explanation__c', 'textlong', required=False,
                 label='If you were eligible for renewal last year and DID NOT apply, please explain why you did not'),
        Question('Expected_Graduation__c', 'date', required=False,
                 label="When do you expect to graduate with a Bachelor's Degree? *",
                 date_range=sv.updated_vars['graduation_range']
                 ),

        Divider('III. Applicant’s Agreement and E-Signature'),
        Divider('If renewed, I understand that if I do not remain in good academic standing, stay enrolled at least part time for the duration of my studies, and participate in some Dream Project activities, I risk forfeiting any subsequent Dream Project Scholarship funding', id=''),
        Question('E_Signature', 'textshort',
                 label='E-signature *', required=False,),
    ],
    'Summit-Assessment': [
        Question('1', 'likert',
                 label='I feel hopeful about my future. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('2', 'likert',
                 label='I am important to my community. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('3', 'likert',
                 label='I know where to look for help when I have an issue. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('4', 'likert',
                 label='With a college degree, my life in the U.S. will improve. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('5', 'likert',
                 label='My story is important and has value. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('6', 'likert',
                 label='I am familiar with immigration laws. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('7', 'likert',
                 label='I know where to find help when I am challenged by my status. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('8', 'likert',
                 label='I know many ways to deal with stress. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('9', 'likert',
                 label='There are a lot of people who are in my situation. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('10', 'likert',
                 label='I am confident about financing my education. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Divider("Summit Kickoff"),
        Question('11', 'likert',
                 label='What is your level of satisfaction with the Kick-off event?',
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('12', 'textlong',
                 label="Which elements of the event did you like the most?",
                 required=False),
        Question('13', 'textlong',
                 label="What, if anything, did you dislike about this event?",
                 required=False),
        Question('14', 'choice',
                 label='Are you likely to participate in a inperson summit event in the future?',
                 choices=[
                     ("Yes", "Yes"),
                     ("No", "No"),
                 ]),
        Question('15', 'likert',
                 label="If you attended, how likely are you to encourage others to attend the Kickoff event?",
                 choices=sv.likert5,
                 scale='likely',
                 required=False),
        Divider("Virtual Sessions"),
        Question('16', 'textshort',
                 label="How many sessions did you attend?",
                 required=False),
        Question('17', 'likert',
                 label="Please rate 'Self-Love Matters: Managing our Health and Wellness in Challenging Times'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('18', 'likert',
                 label="Please rate 'Interviewing & Personal Branding'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('19', 'likert',
                 label="Please rate 'Legal Information Session (English)'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('20', 'likert',
                 label="Please rate 'Job/Internship Search: With our without documentation'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('21', 'likert',
                 label="Please rate 'Beyond 12'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('22', 'likert',
                 label="Please rate 'Networking'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('23', 'likert',
                 label="Please rate 'Financial Literacy'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('24', 'likert',
                 label="Please rate 'Additional Scholarship resources and financial aid'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('25', 'likert',
                 label="Please rate 'Organizing your time'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('26', 'likert',
                 label="Please rate 'Graduate School'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('27', 'likert',
                 label="Please rate 'Starting your own business: With or without documentation'",
                 choices=sv.likert5,
                 scale='numbers',
                 required=False),
        Question('28', 'textlong',
                 label="What, if anything, did you dislike about any of the sessions you attended?",
                 required=False),
        Question('29', 'textlong',
                 label="How can we improve our summit?",
                 required=False),
    ],
    'general': [
        "Please answer to the best of your ability and truthfully. NOTE THAT THESE RESPONSES WILL NOT BE CONSIDERED BY THE COMMITTEE WHEN AWARDING SCHOLARSHIPS!",
        Question('1', 'likert',
                 label='I feel hopeful about my future. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('2', 'likert',
                 label='I will be successful in the United States. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('3', 'likert',
                 label='I will be happy. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('4', 'likert',
                 label='I care about my community. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('5', 'likert',
                 label='I am important to my community. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('6', 'likert',
                 label='I can rely on my community. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('7', 'likert',
                 label='I know where to look for help when I have an issue. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('8', 'likert',
                 label='I have people who I can count on. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('9', 'likert',
                 label='I will not succeed in college. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('10', 'likert',
                 label='With a college degree, my life in the U.S. will improve. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('11', 'likert',
                 label='My story is important and has value. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('12', 'likert',
                 label='I have the power to help others by sharing my experiences. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('13', 'likert',
                 label='I am familiar with immigration laws. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('14', 'likert',
                 label='My immigration status will inevitably lead to failure. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('15', 'likert',
                 label='I know where to find help when I am challenged by my status. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('16', 'likert',
                 label='I can manage my emotions well. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('17', 'likert',
                 label='I do not know many ways to deal with stress. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('18', 'likert',
                 label='There are a lot of people who are in my situation. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('19', 'likert',
                 label='Nobody understands my situation. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('20', 'likert',
                 label='I am confident about financing my education. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('21', 'likert',
                 label='I do not know how I will pay for college. *',
                 choices=sv.likert5,
                 scale='agree5'),
    ],
    'acceptance': [
        Divider('College Information'),
        Question('college', 'textshort',
                 label='What college will you be attending in the fall? *'),
        Divider("<b>We need your Student ID in order to award the scholarship. Without it, we are unable to pair each student with their scholarship. If you do not have your student ID yet, please enter N/A below.</b>", id=''),
        Question('student_id', 'textshort',
                 label='Student ID *'),
        Question('employed', 'choice',
                 label='What is your anticipated employment status during fall semester?*',
                 choices=sv.employ),
        Question('major', 'textshort', label='What is your Major(s)? *'),
        Question('minor', 'textshort', required=False,
                 label='What is your Minor(s)?'),
        Question('graduation_year', 'choice',
                 label="What year do you expect to graduate with a Bachelor's Degree? *",
                 choices=list_dub(updated_vars['graduation_years'])),
        Question('graduation_year_a', 'choice',
                 label="If you are at a community college, what year do you expect to graduate with an Associate's Degree?",
                 choices=list_dub(updated_vars['graduation_years']), required=False),
        Divider('Other Information'),
        Question('pic', 'file',
                 label='Please upload a picture of you that is clear and high resolution *'),
        Question('parents', 'choice',
                 label="Would your parents be interested in getting involved with our Parents' Committee? *",
                 choices=[
                     dub('No'),
                     dub('Yes'),
                 ],),
        Divider(),
        Divider("""<p class='title'>Dream Project Privacy Policy</p>
                <br>
                At all times and in all circumstances, the privacy and safety of our students, scholars, mentees, and their families is of paramount importance.<br><br>

                On all material available to the public, we will only use first names and initial of last or family name. Complete family or last names will never be used. This includes labels or captions on photographs, attribution of quoted words, personal stories, or lists of any sort. This covers social media, Dream Project website, and printed materials.<br><br>

                Photographs of individuals alone or in groups will only identify subjects by first name and first initial of last or family name. Before any group photo, students, scholars, mentees, and family members will be affirmatively reminded to move out of the photo if they do not want to appear. Individual photos will be made public only with explicit permission.<br><br>

                Before beginning (or continuing) in the Mentoring Program, before applying for Dream Project Scholarships (beginning 2020), upon the granting of initial or renewal scholarships (starting 2018), before participating in the Summer Summit (starting 2018), Holiday party or other activities where photographs may be taken, each participant will be given a copy of this policy and a release form to authorize whether photographs or quotes may or may not be used. This form will be signed by a parent or guardian for any participant not yet age 18.
                """,
                id='form-text'),
        Question('release', 'choice',
                 label='Please select one of the following *',
                 choices=[
                     dub('It is OK to use my words or photograph.'),
                     dub('I do NOT want my words or photograph used in ANY way.'),
                     dub('It is OK to use my words but not my photograph.'),
                     dub('It is OK to use my photograph but not my words.'),
                 ]),
        Divider(),
        Divider(
            f"""<p class='title'>Scholarship Agreement</p><br>
                We are pleased that you have been awarded a {updated_vars['scholarship_amount']} Dream Project scholarship for the {updated_vars['summer_fall_s']}-{updated_vars['spring_s']} academic year. Be sure to read the acceptance email <i>very</i> carefully. Before your school can receive the scholarship award you must agree to the following terms:<br>
                <ol>
                    <li>Pursue your degree and will remain in good academic standing with at least a 2.5 GPA;</li>
                    <li>Make continuous satisfactory progress toward completion of the degree;</li>
                    <li>If you are pursuing a two-year associates degree, complete the degree in no more than three years; if you are pursuing a bachelor’s degree, complete the degree in no more than six years;</li>
                    <li>Participate in various Dream Project activities throughout the year. Due to the Covid-19 crisis, we cannot currently provide definitive information about these activities. However, you will participate in at least one Dream Project event, if held, including the Summer Summit, Holiday Dinner or Spring Concert. If these events do take place, and you are unable to participate because of distance, you must seek and obtain permission from the Executive Director;</li>
                    <li>Give a timely response to the annual survey conducted of all Dream Scholars, without any exception;</li>
                    <li>Provide the name and address of the school and your student ID number to the Dream Project as soon as possible since the scholarship check will be sent to your school;</li>
                    <li>Complete and return the enclosed acceptance form.</li>
                    <li>Thanks to the generous support of the Molly and Joseph Herman Foundation, you are eligible to apply for an emergency loan up to $2,000; for more information email Carlos at carlos@dreamproject-va.org.</li>
                    <li>You are eligible to receive an initial free legal consultation regarding immigration-related questions from an immigration attorney on the Dream Project Board of Directors by contacting Carlos at carlos@dreamproject-va.org.</li>
                </ol>
            """,
            id='form-text'),
        Divider("<p style='text-align:center !important; color:red; margin: 20px auto; font-weight: bold'>If you have read, understand, and agree to the everything in this acceptance form please sign your name below.</p>", id=''),
        Question('sig', 'textshort', label='E-signature *'),
    ],
    'parent_contact': [
        Divider('Parent Contact'),
        Question('First Name', 'textshort'),
        Question('Last Name', 'textshort'),
        Question('Email', 'email'),
        Question('Phone Number', 'phone'),
        Divider('Home Address', id=''),
        Question('Street', 'textshort'),
        Question('City', 'textshort'),
        Question('State', 'textshort'),
        Question('Zip', 'textshort', label='Zip Code *'),
    ],
    'mentoring_assessment': [
        Question('1', 'likert',
                 label='I can complete a college application by myself.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('2', 'likert',
                 label='I can understand the requirements for applying to college.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('3', 'likert',
                 label='I can write a college essay to tell my personal story.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('4', 'likert',
                 label='I can find scholarships that I qualify for.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('5', 'likert',
                 label='I can negotiate a financial package with an admissions representative.',
                 choices=sv.likert4,
                 scale='agree4'),
    ],
    'mentoring_assessment_2': [
        Question('1', 'likert',
                 label='I can complete a college application by myself.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('2', 'likert',
                 label='I can understand the requirements for applying to college.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('3', 'likert',
                 label='I can write a college essay to tell my personal story.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('4', 'likert',
                 label='I can find scholarships that I qualify for.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('5', 'likert',
                 label='I can negotiate a financial package with an admissions representative.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('6', 'likert',
                 label='I enjoyed being a part of the mentoring program.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('7', 'likert',
                 label='I felt comfortable talking to my mentor',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('8', 'likert',
                 label='I felt comfortable talking to Ms. Sanguinetti, our mentoring coordinator.',
                 choices=sv.likert4,
                 scale='agree4'),
        Question('9', 'textlong',
                 label='What did you like best about the mentoring program?',
                 required=False),
        Question('10', 'textlong',
                 label='What aspects of the Dream Project mentoring program would you like to improve?',
                 required=False),
    ],
    'mentoring_sign_up': [
        Divider('I. Personal Information:'),
        Question('First Name', 'textshort'),
        Question('Last Name', 'textshort'),
        Question('Country of Birth', 'textshort'),
        Question('Ethnicity', 'choice', choices=sv.ethnicity),
        Question('Birth Date', 'date'),
        Question('Phone', 'phone'),
        Question('Email', 'email'),
        Question('Employment Status', 'choice', choices=sv.employ),

        Divider('II. School Information'),
        Question('high_school', 'textshort',
                 label="Name of the high school you are attending"),
        Question('grade', 'choice',
                 label=f"What grade will you be in during the {updated_vars['summer_fall_s']}-{updated_vars['spring_s']} school year?", choices=[('11', '11'), ('12', '12')]),
        Question('GPA', 'number', label='High School GPA *',
                 max_digits=3, decimal_places=2),
        Question('interested_in', 'multiplechoice',
                 label='Interested Field of Study *',
                 choices=[dub('Undecided/Unsure'),
                          dub('Health/Healthcare'),
                          dub('Business'),
                          dub('Education/Teaching'),
                          dub('Art/Humanities'),
                          dub('Social Sciences'),
                          dub('STEM (Science, tech, engineering, and math'),
                          dub('Not interested'), ]),
        Question('dream_schools', 'textlong', required=False,
                 label="Name of Dream College/Colleges"),
        Question('number_of_applications', 'choice',
                 label='How many colleges are you considering applying to? *', choices=[('Not Sure', 'Not Sure'), ('1 - 2', '1 - 2'), ('3 - 5', '3 - 5'), ('5 or more', '5 or more')]),

        Divider('III. Federal Student Aid'),
        Question('fafsa', 'choice',
                 label='Are you eligible for Federal Student Aid? To be eligible for Federal Student Aid you must be a U.S. citizen or an eligible noncitizen and have a valid Social Security number. In rare cases, some students are allowed to file the FAFSA form, but are ineligible to receive Federal Aid. *', choices=[dub(''), dub('Not Sure'), dub('Yes'), dub('No')]),

        Divider('IV. Finish and Submit'),
        Question('learned_of_dp', 'textshort',
                 label="How did you learn about the Dream Project's Mentoring Program?"),
        Question('available', 'choice',
                 label=f"Are you available Tuesday's 5-7pm starting in the Fall of {updated_vars['summer_fall_s']}?", choices=[('Yes', 'Yes'), ('No', 'No')]),
        Divider("<b style='color:gold; font-size: 24'>After this page you will be redirected to a short mentoring survey. Please complete it to finish your registration!</b>", id='')
    ],
    'fall-survey-scholars': [
        "",
        Divider('I. College Information'),
        Question('1', 'choice',
                 label='Are you receiving, or have received, financial aid from your college or university? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('2', 'choice',
                 label='Other than the Dream Project scholarship, are you receiving, or have received, other scholarships? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('3', 'textlong', required=False,
                 label='If you received other scholarships, please list them and estimate their annual value'),
        Question('4', 'multiplechoice', required=False,
                 label='If you have been able to stay in school, what has allowed you to do that? Check all that apply',
                 choices=[dub('Financial support from family/friends'),
                          dub('Financial support from the school'),
                          dub('Financial support from other scholarships or insitutions'),
                          dub('Support from guidance counselors or mentoring groups'),
                          dub('In-state tuition'),
                          dub('Able to self-support through work and savings'),
                          dub('Change in immigration status'),
                          dub('Other'), ]),
        Question('5', 'multiplechoice', required=False,
                 label='If you are currently not attending college, why is that the case? Check all that apply',
                 choices=[dub('Already graduated'),
                          dub('Better opportunity that did not require a college degree'),
                          dub('Lack of financial resources'),
                          dub('Need to work'),
                          dub('Need to stay at home and help family'),
                          dub('Lack of guidance or counseling'),
                          dub('Emotional or psychological burdens associated with my immigration status'),
                          dub('No clear career direction'),
                          dub('Uncertainty about U.S. immigration policy'),
                          dub('COVID-19 Pandemic'),
                          dub('Other'), ],),
        Question('6', 'choice',
                 label='Are you considering graduate school or an advanced degree? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('7', 'choice',
                 label='Did you, or do you have a paid job while in college/university? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('8', 'choice',
                 label='While in college were you, or are you currently involved in student organizations, honor societies, professional groups, sports teams, or performance groups? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('9', 'choice',
                 label='Did you, or do you have an internship in college/university? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),

        Divider('II. Dream Project Information'),
        Question('10', 'multiplechoice',
                 label='What additional supports should The Dream Project provide for students like you? *',
                 choices=[dub('College mentoring'),
                          dub('Career guidance'),
                          dub('Help managing problems with my family'),
                          dub('Opportunities to connect with other Dream Project Scholars'),
                          dub('Help connecting to Dreamer organizations on campus'),
                          dub('Other'), ],),
        Question('11', 'multiplechoice',
                 label='What Dream Project programs/activities have you participated in? Check all that apply *',
                 choices=[dub('Mentoring program'),
                          dub('Herman Loan Fund Program'),
                          dub('Emergency Relief Fund'),
                          dub('Fundraising Events'),
                          dub('Dream Summit'),
                          dub('Beyond12 Coaching'),
                          dub('Career Networking Opportunities'),
                          dub('Legal/Immigration Workshops'),
                          dub('Parent Meetings/Networks'),
                          dub('I have not participated in any activities'),
                          dub('Other')]),
        Question('12', 'multiplechoice',
                 label='How could the Dream Scholar Program be improved? Check all that apply *',
                 choices=[dub('Provide larger scholarships'),
                          dub('Provide access to mental health counseling'),
                          dub('Provide legal services'),
                          dub('Provide career guidance'),
                          dub('Provide guidance for students while in college'),
                          dub('No Recommendations'),
                          dub('Other')]),
        Question('13', 'multiplechoice',
                 label='Which of the following activities would you be interested in doing to support the Dream Project and other Dream Scholars? Check all that apply *',
                 choices=[dub('Speak at Dream Project Events'),
                          dub('Become a Mentor'),
                          dub('Provide advice to Scholars who have similar career goals as you'),
                          dub('Serve on a Dream Project Committee'),
                          dub('Become involved in Advocacy work'),
                          dub('Not interested'),
                          dub('Other')]),

        Divider('III. Being an Immigrant and Working'),
        Question('14', 'choice',
                 label='Do you identify with the term "Dreamer"? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('15', 'choice',
                 label='What is your current immigration status? *',
                 choices=sv.status),
        Question('16', 'choice',
                 label='Are you currently employed? Select the most appropriate *',
                 choices=sv.employ),
        Question('17', 'choice',
                 label='If you are currently employed, is your job related to your career interests? *',
                 choices=[dub('N/A'), dub('Yes'), dub('No')]),
        Question('18', 'choice',
                 label='If you have DACA, is your current job dependent on it? *',
                 choices=[dub('N/A'), dub('Yes'), dub('No')]),
        Question('19', 'choice',
                 label='Have you temporarily or permanently lost a job as a result of COVID-19? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('20', 'choice',
                 label='Has one or more of your family members lost their job as a result of COVID-19? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('21', 'choice',
                 label='Have you or any of your family members been diagnosed with COVID-19 in the past 9 months? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('22', 'choice',
                 label='What is your estimated annual income? *',
                 choices=[dub('Less than $5,000 per year'),
                          dub('Between $5,000 and $9,999 per year'),
                          dub('Between $10,000 and $19,999 per year'),
                          dub('Between $20,000 and $29,999 per year'),
                          dub('More than $30,000 per year'),
                          dub('Prefer not to answer')]),
        Question('23', 'choice',
                 label='Do you have access to healthcare? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('24', 'choice',
                 label='In the past year have you experienced food insecurity? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('25', 'choice',
                 label=' In the past year have you experienced housing insecurity? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),

        Divider('IV. Comments'),
        Question('26', 'choice',
                 label='What is the best way to reach you? *',
                 choices=[dub('Email'),
                          dub('Phone - Call'),
                          dub('Phone - Text'),
                          dub('Other')]),
        Question('27', 'textlong', required=False,
                 label='Please share any other thoughts you have about the Dream Project'),

        # Likert
        Question('28', 'likert',
                 label='I am a resilient person. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('29', 'likert',
                 label='The current political situation is difficult for Dreamers in higher education. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('30', 'likert',
                 label='I am part of a strong supportive community that motivates me to succeed. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('31', 'likert',
                 label='My success in college is very important to my family. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('32', 'likert',
                 label='I often feel stressed out in school. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('33', 'likert',
                 label='I often feel depressed and doubt my ability to graduate. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('34', 'likert',
                 label='Finding enough money to pay for college is my greatest challenge. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('35', 'likert',
                 label='I was able to successfully balance school, work, and/or family responsibilities. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('36', 'likert',
                 label='The Dream Project was crucial in helping me get into college *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('37', 'likert',
                 label='The Dream Project was/is crucial for my success in college *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('38', 'likert',
                 label='What is your current level of involvement with the Dream Project? *',
                 choices=sv.likert5,
                 scale='involve5'),
        Question('39', 'likert',
                 label='What is your current level of involvement with the Dreamer organizations at your university? *',
                 choices=sv.likert5,
                 scale='involve5'),
        Question('40', 'likert',
                 label='What is your current level of involvement with Dreamer advocacy work? *',
                 choices=sv.likert5,
                 scale='involve5'),
    ],
    'fall-survey-alumni-1': [
        "",
        Divider('I. Supporting the Dream Project'),
        Question('1', 'multiplechoice',
                 label='Which of the following activities would you be interested in doing to support the Dream Project and other Dream Scholars? Check all that apply *',
                 choices=[dub('Speak at Dream Project Events'),
                          dub('Become a Mentor'),
                          dub('Provide advice to Scholars who have similar career goals as you'),
                          dub('Review scholarship applications'),
                          dub('Serve on a Dream Project Committee'),
                          dub('Become involved in Advocacy work'),
                          dub('Join the Scholars & Alumni Committee'),
                          dub('Not interested'),
                          dub('Other')]),

        Divider('II. Being an Immigrant and Working'),
        Question('2', 'choice',
                 label='What is your current immigration status? *',
                 choices=sv.status),
        Question('3', 'multiplechoice',
                 label='Are you currently employed? Select all that apply *',
                 choices=sv.employ[1:]),
        Question('4', 'choice',
                 label='If you are currently employed, is your job related to your career interests? *',
                 choices=[dub('N/A'), dub('Yes'), dub('No')]),
        Question('5', 'choice',
                 label='If you have DACA, is your current job dependent on it? *',
                 choices=[dub('N/A'), dub('Yes'), dub('No')]),
        Question('6', 'choice',
                 label='Have you temporarily or permanently lost a job as a result of COVID-19? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('7', 'choice',
                 label='Has one or more of your family members lost their job as a result of COVID-19? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('8', 'choice',
                 label='Have you or any of your family members been diagnosed with COVID-19 in the past year? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('9', 'choice',
                 label='What is your estimated annual income? *',
                 choices=[dub('Less than $20,000 per year'),
                          dub('Between $20,000 and $29,999 per year'),
                          dub('Between $30,000 and $39,999 per year'),
                          dub('Between $40,000 and $49,999 per year'),
                          dub('Between $50,000 and $59,999 per year'),
                          dub('Between $60,000 and $69,999 per year'),
                          dub('Between $70,000 and $79,999 per year'),
                          dub('Between $80,000 and $89,999 per year'),
                          dub('Between $90,000 and $99,999 per year'),
                          dub('More than $100,000 per year'),
                          dub('Prefer not to answer')]),
        Question('10', 'choice',
                 label='Do you have access to reliable healthcare? *',
                 choices=[dub(''), dub('No'), dub('Yes')]),
        Question('11', 'choice',
                 label='May we contact you about your post-college and work experiences? *',
                 choices=[dub(''), dub('Yes'), dub('No')]),
        Question('12', 'textlong', required=False,
                 label='Please share any other thoughts you have about the Dream Project'),

        Divider('III. Comments'),
        Question('13', 'choice',
                 label='What is the best way to reach you? *',
                 choices=[dub('Email'),
                          dub('Phone - Call'),
                          dub('Phone - Text'),
                          dub('Other')]),
        Question('14', 'textlong', required=False,
                 label='Please share any other thoughts you have about the Dream Project'),
    ],
    'fall-survey-alumni-2': [
        Divider('IV. Extra Information'),
        Divider("If you are employed please fill out the following information. This information lets us understand more about the post-graduate journey of ours students.", id=""),
        Question('1', 'textshort', label="Who is your current employer?"),
        Question('2', 'textshort', label="What is your current job title?"),
        Question('3', 'textshort',
                 label="How long have you been working at your current job?"),
        Question('4', 'choice',
                 label='What field does your current position fall under?',
                 choices=[
                     dub('Health/Healthcare'),
                     dub('Business'),
                     dub('Education/Teaching'),
                     dub('Art/Humanities'),
                     dub('Social Sciences'),
                     dub('STEM (Science, Tech, Engineering, and Math'),
                 ]
                 ),
        Question('5', 'textlong',
                 label="Please share some of your responsibilities at your current job?"),
        Question('6', 'textlong',
                 label="Please share in the space below a little about your current home or school life/plans."),
        Question('7', 'textlong', label="Early next year the Dream Project will have its strategic planning retreat. What would you like to see from the Dream Project over the next five years?"),
    ],
    'b12-evaluation-first': [
        Question('1', 'likert',
                 label='I consider my first year in college successful so far. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('2', 'likert',
                 label='My Beyond12 coach is helping me find the resources I needed. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('3', 'likert',
                 label='I would recommend Beyond12 to a friend. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('4', 'likert',
                 label='I was prepared for the challenges of attending college. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('5', 'likert',
                 label='My Beyond12 coach is helping me build and sustain a community among college peers. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('6', 'likert',
                 label='I was able to establish a good relationship with my Beyond12 coach. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('7', 'likert',
                 label='I believe my Beyond12 coach understood the challenges I was experiencing. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('8', 'likert',
                 label='To what extent do you attribute your success to Beyond12 coaching? *',
                 choices=sv.likert5,
                 scale='all5'),
        Question('9', 'textlong',
                 label='Can you share an example of how Beyond12 coaching was helpful to you? *'),
        Question('10', 'textlong',
                 label='Please share a way in which the Dream Project or Beyond12 could have been more helpful to you this school year. *'),
    ],
    'b12-evaluation-second': [
        Question('1', 'likert',
                 label='So far, I consider this school year successful. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('2', 'likert',
                 label='My Beyond12 coach is helping me find the resources I needed. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('3', 'likert',
                 label='I would recommend Beyond12 to a friend. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('4', 'likert',
                 label='My Beyond12 coach is helping me build and sustain a community among college peers. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('5', 'likert',
                 label='I have continued to have a good relationship with my Beyond12 coach. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('6', 'likert',
                 label='I believe my Beyond12 coach understood the challenges I was experiencing. *',
                 choices=sv.likert5,
                 scale='agree5'),
        Question('7', 'likert',
                 label='To what extend is having a Beyond12 coach for a second year important to your success? *',
                 choices=sv.likert5,
                 scale='all5'),
        Question('8', 'textlong',
                 label='What has been the benefit to you of having a Beyond12 coach for a second year? *'),
        Question('9', 'textlong',
                 label='How has your experience with your Beyond12 coach been different this year? *'),
        Question('10', 'textlong',
                 label='Please share a way in which the Dream Project or Beyond12 could have been more helpful to you this school year. *'),
    ],
}
